#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python manage.py migrate

export DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"

exec python manage.py runserver_plus 0.0.0.0:8000
