services:
  docs:
    image: wind_for_life_local_docs
    container_name: wind_for_life_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./wind_for_life:/app/wind_for_life:z
    ports:
      - '9000:9000'
    command: /start-docs
