# Generated by Django 5.1.11 on 2025-07-14 14:26

import django.db.models.deletion
import django.utils.timezone
import uuid
import wind_for_life.apps.anemometers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anemometer',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Defines slug, does not take unicode', max_length=100)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Value ranges from -180 to 180', max_digits=9, validators=[wind_for_life.apps.anemometers.models.validate_longitude_range])),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Value ranges from -90 to 90', max_digits=9, validators=[wind_for_life.apps.anemometers.models.validate_latitude_range])),
            ],
            options={
                'verbose_name': 'anemometer',
                'verbose_name_plural': 'anemometers',
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.FloatField(help_text='Speed measurement in knots')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timezone dependant')),
                ('anemometer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='anemometers.anemometer')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
