# Generated by Django 5.1.11 on 2025-07-14 14:26

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anemometers', '0001_initial'),
        ('w4l_tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='w4l_tags.UUIDTaggedItem', to='w4l_tags.W4LTag', verbose_name='Tags'),
        ),
        migrations.AddIndex(
            model_name='reading',
            index=models.Index(fields=['anemometer', 'recorded_at'], name='anemometers_anemome_55b105_idx'),
        ),
    ]
